addSbtPlugin("org.typelevel"  % "sbt-fs2-grpc"        % "2.7.12")
addSbtPlugin("org.typelevel"  % "sbt-tpolecat"        % "0.5.2")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"        % "0.12.1")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"        % "2.5.2")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.10.0")
addSbtPlugin("com.github.sbt" % "sbt-dynver"          % "5.0.1")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"       % "0.12.0")